import { NgModule } from '@angular/core';
import { NzBackTopModule } from 'ng-zorro-antd/back-top';
import { NzEmptyModule } from 'ng-zorro-antd/empty';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzImageModule } from 'ng-zorro-antd/image';
import { NzMessageModule } from 'ng-zorro-antd/message';

@NgModule({
  exports: [
    // NzI18nModule,
    // NzLayoutModule,
    // NzMenuModule,
    NzMessageModule,
    // NzBreadCrumbModule,
    // NzTableModule,
    // NzAffixModule,
    // NzAlertModule,
    // NzAnchorModule,
    // NzAutocompleteModule,
    // NzAvatarModule,
    NzBackTopModule,
    // NzBadgeModule,
    // NzButtonModule,
    // NzCalendarModule,
    // NzCardModule,
    // NzCarouselModule,
    // NzCascaderModule,
    // NzCheckboxModule,
    // NzCollapseModule,
    // NzCommentModule,
    // NzDatePickerModule,
    // NzDescriptionsModule,
    // NzDividerModule,
    // NzDrawerModule,
    // NzDropDownModule,
    NzEmptyModule,
    // NzFormModule,
    // NzGridModule,
    NzIconModule,
    NzImageModule
    // NzInputModule,
    // NzInputNumberModule,
    // NzListModule,
    // NzMentionModule,
    // NzModalModule,
    // NzNoAnimationModule,
    // NzNotificationModule,
    // NzPageHeaderModule,
    // NzPaginationModule,
    // NzPopconfirmModule,
    // NzPopoverModule,
    // NzProgressModule,
    // NzRadioModule,
    // NzRateModule,
    // NzResultModule,
    // NzSelectModule,
    // NzSkeletonModule,
    // NzSliderModule,
    // NzSpaceModule,
    // NzSpinModule,
    // NzStatisticModule,
    // NzStepsModule,
    // NzSwitchModule,
    // NzTabsModule,
    // NzTagModule,
    // NzTimePickerModule,
    // NzTimelineModule,
    // NzToolTipModule,
    // NzTransButtonModule,
    // NzTransferModule,
    // NzTreeModule,
    // NzTreeViewModule,
    // NzTreeSelectModule,
    // NzTypographyModule,
    // NzUploadModule
    // NzWaveModule,
    // NzResizableModule,
    // NzPipesModule
  ]
})
export class NgZorroAntdModule {}
